using AlphaEssWeb.Api_V2.Domain;
using AlphaEssWeb.Api_V2.Model.Dtos;

namespace AlphaEssWeb.Api_V2.Model
{
	internal static class VT_COLDATAExtension
	{
		public static VtColDataDto ToVtColDataDto(this VT_COLDATA cd)
		{
			return new VtColDataDto
			{
				Id = cd.Key,
				Sn = cd.SysSn,
				UploadTime = cd.UploadDatetime,
				Ppv1 = cd.Ppv1,
				Ppv2 = cd.Ppv2,
				Upv1 = cd.Upv1,
				Upv2 = cd.Upv2,
				Ua = cd.Ua,
				Ub = cd.Ub,
				Uc = cd.Uc,
				Fac = cd.Fac,
				Ubus = cd.Ubus,
				PrealL1 = cd.PrealL1,
				PrealL2 = cd.PrealL2,
				PrealL3 = cd.PrealL3,
				Tinv = cd.Tinv,
				PacL1 = cd.PacL1,
				PacL2 = cd.PacL2,
				PacL3 = cd.PacL3,
				InvworkMode = cd.InvworkMode,
				EpvTotal = cd.EpvTotal,
				Einput = cd.Einput,
				Eoutput = cd.Eoutput,
				Echarge = cd.Echarge,
				PmeterL1 = cd.PmeterL1,
				PmeterL2 = cd.PmeterL2,
				PmeterL3 = cd.PmeterL3,
				PmeterDc = cd.PmeterDc,
				Pbat = cd.Pbat,
				Soc = cd.Soc,
				Batv = cd.Batv,
				Batc = cd.Batc,
				FlagBms = cd.FlagBms,
				BmsWork = cd.BmsWork,
				Pcharge = cd.Pcharge,
				Pdischarge = cd.Pdischarge,
				BmsRelay = cd.MsRelay,
				BmsNum = cd.BmsNum,
				VcellLow = cd.VcellLow,
				VcellHigh = cd.VcellHigh,
				TcellLow = cd.TcellLow,
				TcellHigh = cd.TcellHigh,
				IdTempLover = cd.IdTempLover,
				IdTempEover = cd.IdTempEover,
				IdTempediffe = cd.IdTempediffe,
				IdChargcurre = cd.IdChargcurre,
				IdDischcurre = cd.IdDischcurre,
				IdCellvolover = cd.IdCellvolover,
				IdCellvollower = cd.IdCellvollower,
				IdSoclower = cd.IdSoclower,
				IdCellvoldiffe = cd.IdCellvoldiffe,
				BatC1 = cd.BatC1,
				BatC2 = cd.BatC2,
				BatC3 = cd.BatC3,
				BatC4 = cd.BatC4,
				BatC5 = cd.BatC5,
				BatC6 = cd.BatC6,
				ErrInv = cd.ErrInv,
				WarInv = cd.WarInv,
				ErrEms = cd.ErrEms,
				ErrBms = cd.ErrBms,
				ErrMeter = cd.ErrMeter,
				ErrBackupBox = cd.ErrBackupBox,
				EGridCharge = cd.Egridcharge,
				EmsStatus = cd.EmsStatus,
				EDischarge = cd.EDischarge,
				Soc1 = cd.Soc1,
				Soc2 = cd.Soc2,
				Soc3 = cd.Soc3,
				Soc4 = cd.Soc4,
				Soc5 = cd.Soc5,
				Soc6 = cd.Soc6,
				VcellLowValue = cd.VcellLowValue,
				VcellHighValue = cd.VcellHighValue,
				TcellLowValue = cd.TcellLowValue,
				TcellHighValue = cd.TcellHighValue,
				InvBatV = cd.InvBatV,
				BmsShutdown = cd.BmsShutdown,
				BmuRelay = cd.BmuRelay,
				BmsHardVer1 = cd.BmsHardVer1,
				BmsHardVer2 = cd.BmsHardVer2,
				BmsHardVer3 = cd.BmsHardVer3,
				DispatchSwitch = cd.DispatchSwitch,
				Pdispatch = cd.Pdispatch,
				DispatchSoc = cd.DispatchSoc,
				DispatchMode = cd.DispatchMode
			};
		}
	}
}
